export const constants = {
  REDIRECT_URL_ENV: 'VITE_REDIRECT_URL',
  WEBSOCKET_URL_ENV: 'VITE_WEBSOCKET_URL',
  AUTH_URL_ENV: 'VITE_AUTH_URL',
  AUTH_CLIENT_ID_ENV: 'VITE_CLIENT_ID',
  HOME_PAGE_URL_ENV: 'VITE_HOME_PAGE_URL',
  API_URL_ENV: 'API_URL',
};
