name: Aya-Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-aya-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Aya Db Migrations
        run: go build -C aya-backend/db-migration -v

      - name: Build Aya Server
        run: go build -C aya-backend/server -v
